version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/var/www/html
    env_file:
      - .env.docker
    depends_on:
      - db
    networks:
      - laravel

  web:
    image: nginx:stable
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE:-laravel}
      MYSQL_USER: ${DB_USERNAME:-laravel}
      MYSQL_PASSWORD: ${DB_PASSWORD:-laravel}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD:-laravel}
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - laravel

  node:
    image: node:20
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    command: ["npm", "run", "dev"]
    depends_on:
      - app
    networks:
      - laravel

networks:
  laravel:

volumes:
  db-data:
